### PR TITLE
Adding Pipeline Export Endpoint

### PR DESCRIPTION
**Pull request by ibnc**
This PR implements the plugin side of https://github.com/gocd/gocd/pull/5330

Upgraded to v2

### CODE REVIEW

**Comment by tomzo** [comment]
Hi @ibnc,
This will not be that simple as in json plugin.
Yaml keywords and some of the tree structure is different than what comes from gocd server in json. 

I think the right way to implement it, is look at each of the existing `*Transform` classes and implement a reverse operation, and unit test each of them accordingly.

The way you wrote it now, will produce yaml far from what it should be.

**Comment by tomzo** [comment]
BTW, there is no need to add new json and yaml examples in those tests. It would be sufficient to transform each part back from yaml to json. 
The coverage of those examples is nearly 100%

**Comment by ibnc** [comment]
@tomzo 

Ah.... You're right... I didn't notice that many of the field names are different. I was hoping to avoid doing the inverse of the transforms, but it doesn't look like there's really an alternative.

**Comment by ibnc** [comment]
@tomzo How's this looking?

**Comment by tomzo** [comment]
Very good. I looked earlier too.
I think I can merge it after core is ready.

**Comment by ibnc** [comment]
@tomzo cool.

Shouldn't it be good to merge? https://github.com/gocd/gocd/pull/5330 has been merged, and these changes are backwards compatible. Same goes for https://github.com/tomzo/gocd-json-config-plugin/pull/19

**Comment by ibnc** [comment]
@tomzo My only other thought is changing what we return.

So, instead of returning:
```
pipeline_name:
  group: blah
  stages: 
    ...
  ...
```
Return:
```
format_version: 3
pipelines:
  pipeline_name:
    group: blah
    stages:
      ...
    ...
```

I'm going back and forth on which is the best to send back to the go server. The former might be easier to paste into existing yaml files, but the latter would be easier to create new yaml files with... thoughts?

**Comment by tomzo** [comment]
I thought about this too. I think the latter will be better because it has the indentation already at a correct level and users often get this wrong.

**Comment by ibnc** [comment]
@tomzo That makes sense. I'll work on changing that.

Also, I'm gonna work on cleaning up the output. It's a bit messy. Here's an example one from a local test pipeline:

```
pipeline1:
  group: blah
  label_template: ${COUNT}
  lock_behavior: none
  materials:
    git:
      git: git@github.com:ibnc/tablinate.git
      shallow_clone: false
      auto_update: true
      branch: master
  stages:
  - defaultStage1:
      fetch_materials: true
      keep_artifacts: false
      clean_workspace: false
      approval:
        type: success
        roles: [
          ]
        users: [
          ]
      jobs:
        defaultJob1:
          run_instances: '0'
          tabs: {
            }
          resources: [
            ]
          artifacts: [
            ]
          properties: {
            }
          tasks:
          - exec:
              arguments: [
                ]
              command: ls
              run_if: passed
  parameters: {
    }
```
All of those empty lists/hashes are super messy and make it hard to read

**Comment by tomzo** [comment]
Yes, thank you. That's a good point. 
If you can, try to not emit default values too.

Also we should not emit `parameters` and `stages` at the same time.
BTW, there is a corner case of exporting a pipeline which references an XML template. That might be worth looking at too.

**Comment by ibnc** [comment]
I'll look into the default values

Why shouldn't we emit parameters and stages at the same time? Are they mutually exclusive?

Could you give an example of the xml corner case?

**Comment by tomzo** [comment]
> I'll look into the default values

It's just a suggestion to shorter the emitted yaml.

> Why shouldn't we emit parameters and stages at the same time? Are they mutually exclusive?

Yes.

You can have a template defined in XML, it does not matter what's in it. Just define any pipeline template via UI. 
Then you can reference that template in yaml as in https://github.com/tomzo/gocd-yaml-config-plugin#referencing-an-existing-template-in-a-pipeline

```yaml
mypipe:
  group: group1
  label_template: "foo-1.0-${COUNT}"
  lock_behavior: none
  parameters:
    param1: value
  materials:
    mygit:
      git: http://example.com/mygit.git
  template: template1
```

So `pipeline` should either have:
 * `stages:`
 * Or `template:` and `parameters:`

I am pretty sure either the plugin or server rejects config if both are specified.

**Comment by ibnc** [comment]
@tomzo I don't think params and stages are mutually exclusive. I'm able to create a pipeline with both stages and params, and run the build

**Comment by ibnc** [comment]
The documentation also doesn't specify that they're mutually exclusive, and even gives an example with both stages and params present in the xml (https://docs.gocd.org/current/configuration/admin_use_parameters_in_configuration.html)

**Comment by ibnc** [comment]
@tomzo 
I think this PR is ready to merge unless you see anything that needs to be changed.

Also, here's an example output from a "complex" pipeline:
```
format_version: 3
pipelines:
  params:
    group: blah
    label_template: ${COUNT}
    lock_behavior: none
    environment_variables:
      ee: uuu
    materials:
      git:
        git: git@github.com:ibnc/tablinate.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - defaultStage:
        fetch_materials: false
        keep_artifacts: true
        clean_workspace: true
        approval:
          type: manual
        environment_variables:
          eek: p
        secure_variables:
          eeku: AES:oqD2xYUDANyoPWrMmaJJDQ==:XrMdcBKmft52E84Jqrkm9g==
        jobs:
          defaultJob:
            run_instances: '0'
            tasks:
            - exec:
                arguments:
                - -la
                command: ls
                run_if: passed
          grr:
            run_instances: '0'
            tasks:
            - exec:
                command: ls
                run_if: passed
    - '2':
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          '2':
            run_instances: '0'
            tasks:
            - exec:
                command: ls
                run_if: passed
```

I've confirmed that the above works if pasted into a yaml config file

**Comment by tomzo** [comment]
> The documentation also doesn't specify that they're mutually exclusive, and even gives an example with both stages and params present in the xml 

For config-repos parameters are meaningless if not used with a template.

I really meant that `template:` is mutually exclusive with `stages:`. But we are good then.

@ibnc Thank you for writing and testing all this. I wanted to see that example before merging. It looks good. I'll merge this tomorrow because it's bad luck to merge at midnight.

**Comment by arvindsv** [comment]
Is `run_instances: '0'` the default, and so not necessary?

**Comment by tomzo** [comment]
@arvindsv I've fixed that default `run_instances: '0'` myself.

**Pull request merged**
