### PR TITLE
Change whitelist to includes

### PR DESCRIPTION
**Pull request by arvindsv**
Also:

- Fixes old "whitelist" behaviour, which was not working at all (https://github.com/tomzo/gocd-yaml-config-plugin/commit/1bdcd91c19d5de333be668e04d116e16ffed58f9).
- Expects input for filter to be `includes` instead of the old `whitelist` (related to https://github.com/gocd/gocd/pull/8266).
- Exports YAML with `target_version: 9` (see https://github.com/tomzo/gocd-yaml-config-plugin/issues/140).

- Need to discuss about what / if we can change the usage of `blacklist` / `whitelist` in the YAML itself. Seems to be the first time we need to change the YAML format in a way that old files can stop working if we're not careful. So, this PR just makes sure that the pipeline export works fine. [To be clear: This PR does _not_ add support for `target_version: 10`, which does not really mean anything to the YAML plugin anyway, since we haven't decided what needs to happen to the usages of `blacklist` / `whitelist` in this case].

Testing:

1. Test fixture `complete.git` was changed to verify this functionality.

2. Manually:

    1. Took the input JSON mentioned in https://github.com/gocd/gocd/pull/8266#issuecomment-656233490 and set it up in a config repo to be used by the JSON config plugin.
    2. Exported the pipeline to JSON (to get a canoncial JSON).
    3. Exported that pipeline to YAML as well.
    4. Removed the JSON (from step 1), refreshed the JSON repo so that no pipelines come from it and then set up a YAML config repo and used the YAML mentioned in step 3.
    5. Exported the pipeline to JSON.
    6. Compared the two JSON outputs (step 2 and step 5) and they were identical.

<details>
    <summary>For step i: Input JSON</summary>

```json
{
  "format_version" : 1,
  "name": "p1",
  "environment_variables": [],
  "group" : "group1",
  "materials": [
    {
      "url": "https://github.com/arvindsv/faketime.git",
      "type": "git",
      "name": "git_material1",
      "destination": "dir1",
      "filter": {
        "whitelist": [
          "dir1",
          "dir2"
        ]
      }
    },
    {
      "url": "https://github.com/arvindsv/faketime2.git",
      "type": "git",
      "name": "git_material2",
      "destination": "dir2",
      "filter": {
        "ignore": [
          "dir1",
          "dir2"
        ]
      }
    },
    {
      "url": "https://github.com/arvindsv/faketime2.git",
      "type": "git",
      "name": "git_material3",
      "destination": "dir3"
    }
  ],
  "stages": [
    {
      "name": "build",
      "fetch_materials": true,
      "never_cleanup_artifacts": false,
      "clean_working_directory": false,
      "environment_variables": [],
      "jobs": [
        {
          "name": "build",
          "environment_variables": [],
          "tabs": [],
          "resources": [],
          "artifacts": [],
          "properties": [],
          "run_instance_count": null,
          "timeout": 0,
          "tasks": [
            {
              "type": "rake"
            }
          ]
        }
      ]
    }
  ]
}
```

</details>

<details>
    <summary>For step ii: Exported JSON</summary>

```json
{
  "group": "group1",
  "name": "p1",
  "display_order_weight": -1.0,
  "label_template": "${COUNT}",
  "lock_behavior": "none",
  "environment_variables": [],
  "parameters": [],
  "materials": [
    {
      "url": "https://github.com/arvindsv/faketime.git",
      "branch": "master",
      "shallow_clone": false,
      "filter": {
        "ignore": [],
        "includes": [
          "dir1",
          "dir2"
        ]
      },
      "destination": "dir1",
      "auto_update": true,
      "name": "git_material1",
      "type": "git"
    },
    {
      "url": "https://github.com/arvindsv/faketime2.git",
      "branch": "master",
      "shallow_clone": false,
      "filter": {
        "ignore": [
          "dir1",
          "dir2"
        ],
        "includes": []
      },
      "destination": "dir2",
      "auto_update": true,
      "name": "git_material2",
      "type": "git"
    },
    {
      "url": "https://github.com/arvindsv/faketime2.git",
      "branch": "master",
      "shallow_clone": false,
      "filter": {
        "ignore": [],
        "includes": []
      },
      "destination": "dir3",
      "auto_update": true,
      "name": "git_material3",
      "type": "git"
    }
  ],
  "stages": [
    {
      "name": "build",
      "fetch_materials": true,
      "never_cleanup_artifacts": false,
      "clean_working_directory": false,
      "approval": {
        "type": "success",
        "users": [],
        "roles": [],
        "allow_only_on_success": false
      },
      "environment_variables": [],
      "jobs": [
        {
          "name": "build",
          "environment_variables": [],
          "tabs": [],
          "resources": [],
          "artifacts": [],
          "timeout": 0.0,
          "tasks": [
            {
              "run_if": "passed",
              "type": "rake"
            }
          ]
        }
      ]
    }
  ]
}
```

</details>

<details>
    <summary>For step iii: Exported YAML</summary>

```yaml
format_version: 9
pipelines:
  p1:
    group: group1
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git_material1:
        git: https://github.com/arvindsv/faketime.git
        whitelist:
        - dir1
        - dir2
        shallow_clone: false
        auto_update: true
        branch: master
        destination: dir1
      git_material2:
        git: https://github.com/arvindsv/faketime2.git
        blacklist:
        - dir1
        - dir2
        shallow_clone: false
        auto_update: true
        branch: master
        destination: dir2
      git_material3:
        git: https://github.com/arvindsv/faketime2.git
        shallow_clone: false
        auto_update: true
        branch: master
        destination: dir3
    stages:
    - build:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          build:
            timeout: 0
            tasks:
            - rake:
                run_if: passed
```

</details>

<details>
    <summary>For step v: New JSON exported from pipeline created via YAML</summary>

```json
{
  "group": "group1",
  "name": "p1",
  "display_order_weight": -1.0,
  "label_template": "${COUNT}",
  "lock_behavior": "none",
  "environment_variables": [],
  "parameters": [],
  "materials": [
    {
      "url": "https://github.com/arvindsv/faketime.git",
      "branch": "master",
      "shallow_clone": false,
      "filter": {
        "ignore": [],
        "includes": [
          "dir1",
          "dir2"
        ]
      },
      "destination": "dir1",
      "auto_update": true,
      "name": "git_material1",
      "type": "git"
    },
    {
      "url": "https://github.com/arvindsv/faketime2.git",
      "branch": "master",
      "shallow_clone": false,
      "filter": {
        "ignore": [
          "dir1",
          "dir2"
        ],
        "includes": []
      },
      "destination": "dir2",
      "auto_update": true,
      "name": "git_material2",
      "type": "git"
    },
    {
      "url": "https://github.com/arvindsv/faketime2.git",
      "branch": "master",
      "shallow_clone": false,
      "filter": {
        "ignore": [],
        "includes": []
      },
      "destination": "dir3",
      "auto_update": true,
      "name": "git_material3",
      "type": "git"
    }
  ],
  "stages": [
    {
      "name": "build",
      "fetch_materials": true,
      "never_cleanup_artifacts": false,
      "clean_working_directory": false,
      "approval": {
        "type": "success",
        "users": [],
        "roles": [],
        "allow_only_on_success": false
      },
      "environment_variables": [],
      "jobs": [
        {
          "name": "build",
          "environment_variables": [],
          "tabs": [],
          "resources": [],
          "artifacts": [],
          "timeout": 0.0,
          "tasks": [
            {
              "run_if": "passed",
              "type": "rake"
            }
          ]
        }
      ]
    }
  ]
}
```

</details>

### CODE REVIEW

**Comment by tomzo** [comment]
@arvindsv thanks for the fixes and updates!

Regarding the breaking change of whitelist to includes - I think, the plugin should still accept the whitelist/blacklist keywords but in the documentation we could mark it as deprecated. Otherwise we are forcing users to migrate all their config repos at once. format_version: 10 should be probably a separate PR.

**Comment by arvindsv** [comment]
@tomzo I agree. I'll try and work on it soon. Will let it accept both. Will open a separate PR.

**Comment by arvindsv** [comment]
@tomzo If this looks ok, can you merge it? That way, it can be bundled with the next release. I'll try and get to the new PR this weekend.

**Comment by tomzo** [comment]
Thanks. I'll be doing a bit of maintenance during the weekend too. The build is currently failing due to minor errors from previous PR. But I plan to cut a release soon

**Pull request merged**
