### PR TITLE
Adding syntax to configure new scms

### PR DESCRIPTION
**Pull request by ibnc**
Syntax side of https://github.com/gocd/gocd/issues/5694
Example from tests:
```
myPluggableGit:
  plugin_configuration:
    id: plugin_id
    version: 1
  destination: destinationDir
  options:
    url: url
  blacklist:
    - dir1
    - dir2
```

### CODE REVIEW

**Comment by ibnc** [comment]
@tomzo thoughts?

**Comment by tomzo** [comment]
Looks OK. I wanted to add some docs, but got busy with other things.

**Comment by ibnc** [comment]
@tomzo I'm actually writing some docs right now. Should I push them up into this PR?

**Comment by ibnc** [comment]
@tomzo Here's the draft of the addition to the README


Since GoCD `>= 19.2.0` defining new pluggable materials that are not defined 
in the go server is supported.

```
myPluggableGit:
  plugin_configuration:
    id: plugin_Id
    version: plugin_version
  options:
    url: git@github.com:tomzo/gocd-yaml-config-plugin.git
  destination: destinationDir
  blacklist:
    - dir1
    - dir2
```

**Comment by arvindsv** [comment]
Go => GoCD, please, wherever possible. It's just easier to search for. :)

**Comment by ibnc** [comment]
@tomzo Should we bump the `format_version`

**Comment by tomzo** [comment]
No need to bump format_version since this is not breaking any previous syntax, just adding a new definition.

**Comment by arvindsv** [comment]
@tomzo What about this case?

1. Old GoCD server: Say 18.12.
2. New plugin.
3. A YAML file with existing `format_version` (I guess it's `2`?) and the new SCM.

When the server parses it, in the best case, it'll fail. In the worst case, it'll ignore that SCM, right? And not show any warnings or indications.

**Comment by tomzo** [comment]
> When the server parses it, in the best case, it'll fail. In the worst case, it'll ignore that SCM, right?

Yes, it would fail with non-obvious error message, 2 cases are:
 - when user specified scm definition but not `scm_id` - it would fail saying that `scm_id` is required to reference.
 - when user specified scm definition and `scm_id` then gocd would fail saying that SCM is not defined.

I don't think there is a case of just ignoring the material.

So we can bump if we want that error instead to say `format_version: 4 is not supported by GoCD 18.12`.

Btw, current version is `3`.

**Comment by arvindsv** [comment]
> I don't think there is a case of just ignoring the material.

Ok, good.

**Pull request merged**
