### PR TITLE
weird pipeline config/progression need

### PR DESCRIPTION
**Pull request by plainsane**
first off, i do not expect you to accept this PR.  im really using it to begin a dialogue.

i work in an environment that has a very specific branching structure and a need for any and all things to travel this branching structure for the sake of security.

im using this plugin to leverage anchors to a high degree to keep multiple pipelines' behaviors in sync.

basically, i deploy code into multiple environments where each environment is its own aws account.  but the pipelines require different environmental config which is why i have a pipeline per environment (maybe gocd environments could help, but im missing it if they can) but using anchors for everything except environment variables to prevent snowflaking.  i hope this provides a decent description of my current state.  i can probably mock up an example to show you what im doing if needed.

the issue i have run into is that because all pipelines are defined in the same yaml file when i commit changes to my anchors, those changes go hot for every pipeline.  but i need to stagger the changes to the pipeline so they can progress through at the same rate as the "infrastructure as code" the pipeline is managing.  for example, i just finished a sprint that had to rework the flow of the pipeline to fail a specific resource before upgrade (didnt know that was coming).  this resource does not live in prod yet, so i do not want to risk "check for existence" errors from stopping production for a previous sprint that is about to go out to prod tomorrow.

this pull request adds a tag to the pipeline definition and a config option to pick up only pipelines with that tag.  the reason im doing this (and it may be stupid) is so that i can have a repo with my pipelines for all environments, BUT, when i commit to the dev branch, i have a plugin setting for the configrepo on the dev branch, only pick up pipelines tagged with dev.  so that way none of my qa/production pipelines are effected until i merge that branch upward, but i can fully test in lower environments first.

honestly, i hate the idea of putting a "tag" value in the plugin configuration, but i could not figure out (due to time pressure) how to get the branch name of the config repo from the cruise-control.xml file.

### CODE REVIEW

**Comment by tomzo** [comment]
Hi @plainsane 
The issue seems legit. If I am getting this right, you basically need to run the pipeline configuration on development branch to see that it passes. Then when you are confident that configuration on dev branch is solid, you merge dev branch into e.g. production. After the merge to production pipeline configuration should change to what was in dev. Except that you have different secrets.
But when changes are pushed to dev branch are made you don't want to see any them on production.

> how to get the branch name of the config repo from the cruise-control.xml file.

You cannot because config-repo extension point on server does not provide it to the plugin when it's asking to parse directory. I did consider adding it, but at the time I didn't see a use case for it. You can see me mentioning it in https://github.com/gocd/gocd/pull/2432

The way I see such scenario working is this:
On gocd server xml we define config-repo for each environment
```xml
    <config-repo pluginId="yaml.config.plugin" id="dev">
      <git url="url" branch="dev" />
    </config-repo>
    <config-repo pluginId="yaml.config.plugin" id="prod">
      <git url="url" branch="prod" />
    </config-repo>
```
The configuration yaml looks like this:
```yaml
pipelines:
  app.{branch}: # branch gets replaced by yaml plugin
  # just define pipeline as required
```
Above config results in 2 pipelines named `app.dev` and `app.prod`. When you merge dev to prod, then no changes are required in the yaml, and configuration in `prod` becomes the same as in was in `dev`.
For secrets you can assign each pipeline to specific environment and set secrets per environment there. It does not need to be in yaml, although it still can be.

Above setup requires to implement:
 - on gocd server: sending branch name (and perhaps other material properties to the config-repo plugin)
 - in yaml plugin: implement some sort of expansion/usage of those properties.

What do you think?
Maybe I missed something, would it solve your case?

**Comment by plainsane** [comment]
no, you nailed it, i like the app.{branch} sooooo much better than my hacky get out of jail free card, if i could use the same expansion to assign the environment, as our branches coincide with environments.

honestly, a more general expansion syntax would be super awesome anyways (for dev i dont want manual approval, but for production due to SOX i do).

**Comment by plainsane** [comment]
also, is it possible to assign all agents to a group?  currently for a short period of time, our agents are treated as cattle, they get destroyed and auto registered almost daily, having to specify a guid would be come very tedious.  if not i can bang around it most likely, maybe force my bootstrap script to generate consistent guids.

eventually these will be moved to elastic agents, but i just dont have the time at the moment.

**Comment by plainsane** [comment]
with your approach, we will need the expansion on the key side and the value side.
i have a value stream of about 9 value streams that hook together so if the pipeline names are auto generated, i will need to specify the same generated name on the value side of a pipeline material.

**Pull request closed without merging**
