### PR TITLE
Update & modernize build and dependencies

### PR DESCRIPTION
**Pull request by chadlwilson**
This PR modernizes the plugin build and dependencies
* Upgrades to Gradle 7 incl. required plugin + compatibility changes
* Bumps all test dependencies to latest versions, along with required compatibility changes
* Bumps included dependencies to patched versions without published vulnerabilities

I've compared to built jar before-and-after and everything looks in tact. There are no changes to production code, but wanted to bump the version notably due to the dependency changes.

Appreciate if you can take a look @tomzo. Given this is bundled with GoCD I think we need to ensure it's somewhat up-to-date.

### CODE REVIEW

**Comment by tomzo** [comment]
Thanks Chad.
I've made a minor tweak on top of this to use gradlew in the build scripts.
I've released the new version as well.
Cheers

**Comment by chadlwilson** [comment]
Wow, thanks! Will take a look.

Will also take a look at the json plugin too at some point.

**Comment by chadlwilson** [comment]
It looks like there might have been an old tag for `0.14.0` as https://github.com/tomzo/gocd-yaml-config-plugin/compare/0.13.0...0.14.0 doesn't really display the right stuff. Do we need to bump the version to `0.14.1` or something perhaps, or you want to fix the tags?

**Comment by chadlwilson** [comment]
I've [updated to this released version](https://github.com/gocd/gocd/pull/10645) on https://build.gocd.org/ and it's now running there. It seems OK.

Other than addressing the tag/version, are you able to mark the release as non-pre-release when you're comfortable? I'd like to do a GoCD release shortly, so doing a round of updating the pre-bundled plugins.

**Comment by tomzo** [comment]
Thanks Chad. I've fixed the tag just now

**Pull request merged**
