### PR TITLE
Add ability to control display order of pipelines on the GoCD dashboard

### PR DESCRIPTION
**Pull request by arvindsv**
* Introduce display_order_weight.
* Update README to reflect that a UI is now available to configure config repositories.
* Clarify usage of format_version.
* Code changes and tests.

@tomzo Haven't bumped the version, since this is at 0.9.0 already. Do you want: `0.10.0`? `1.0.0`? Wasn't sure.

Related to https://github.com/gocd/gocd/pull/6043

### CODE REVIEW

**Comment by tomzo** [comment]
Going with the concise design of this plugin, the keywords should be as short and meaningful as possible. I think `display_order_weight` is OK at contract level, but how about just `display_order` in yaml?

As for version please run `./tasks.sh set_version 0.10.0`. If that does not work on mac, let me know.

**Comment by arvindsv** [comment]
@tomzo Sounds good. I can pick `display_order`. Why I added `weight` to it, at least in the contract, is because it's not truly the display order. Two pipelines can have the same order. If you're sure it won't lead to confusion, I'll do it. Let me know.

I bumped the version up to `0.10.0`. It worked. I'll wait to hear from you about the `display_order`. Thank you!

**Comment by tomzo** [comment]
Let's go with `display_order`, I don't think anyone will be confused what that means as long as the docs state the usage.

**Comment by arvindsv** [comment]
Sounds good. Will make that change.

**Comment by arvindsv** [comment]
@tomzo Can you take a look again, please?

**Comment by tomzo** [comment]
All good.
Thank you.

**Pull request merged**
