### PR TITLE
Adds GoCD template support

### PR DESCRIPTION
**Pull request by lobsterdore**
Adds ability to specify GoCD templates from YAML, not working
currently.

### CODE REVIEW

**Comment by lobsterdore** [comment]
@tomzo I can't seem to get this functionality working so perhaps you can point me in the right direction?

I've copied and paired down the pipeline parser in order to support templates, however I cannot get templates to appear in GoCD using this test repo - https://github.com/lobsterdore/gocd-yaml-tester/blob/master/template.gocd.yaml.

I've done some debugging and I can see that the YAML config plugin is indeed collecting all the template configuration from the test repo, however it never seems to wind up in GoCD, I don't know much about GoCD or it's plugin architecture so I feel like I am missing a piece of the puzzle here, do I need to update an API request somewhere? I've searched through this plugin and I can't seem to find the answer.

**Comment by tomzo** [comment]
Hi @lobsterdore 

> I don't know much about GoCD or it's plugin architecture so I feel like I am missing a piece of the puzzle here, do I need to update an API request somewhere? I've searched through this plugin and I can't seem to find the answer.

I'm afraid there is much more to be changed on the server side than in the plugin. Most of config-repo functionally is actually implemented there as part of https://github.com/gocd/gocd/issues//1133 and all PRs related. 
For start, the current model of a `config-repo` on server side defines configuration as a merge of XML elements and **exactly one** external source control repository. So introducing templates requires to start at changing that assumption.
There is an issue of handling parameters too, I don't see any in your example repository - https://github.com/lobsterdore/gocd-yaml-tester/blob/master/template.gocd.yaml

We have an on-going discussion on improvements to the config-repos in https://github.com/gocd/gocd/issues/5175, including the templates. You should also see #2

**Comment by tomzo** [comment]
> we could extract the parsed templates JSON, use this to update the templates via API calls and then process the rest of the JSON via the plugin APIs.

It could work. But I think that is a hack with possibly a lot of unintended consequences. 
If you want to go this way, you can try. I wouldn't merge that into master, because it would introduce a template model which is likely not maintainable in the future.

If I commit to implementing templates support, I would do it the right way. That was my approach in https://github.com/gocd/gocd/issues/1133 and I stick to this. Otherwise its a lot of workarounds and wasted work in the end.
Btw, I would appreciate your ideas and feedback on how templates should look like, my last thoughts were in [this comment](https://github.com/gocd/gocd/issues/5175#issuecomment-422883413).

For your particular needs - If you are already willing to use API to create templates, then perhaps consider using gomatic or [terraform GoCD provider](https://github.com/beamly/terraform-provider-gocd#gocd_pipeline_template) to do that.

**Comment by lobsterdore** [comment]
@tomzo thanks for the feedback, it's much appreciated. I wasn't aware of Gomatic so I think I will head down that route for now, I will take a look at your comments as well.

Gonna close this PR for now since it's now useful as it stands.

**Pull request closed without merging**
