### PR TITLE
Add a CLI frontend to this jar, making this executatble

### PR DESCRIPTION
**Pull request by marques-work**
Hi @tomzo, this PR is related to https://github.com/gocd/gocd/issues/5175#issue-360963403 (idea 4), which is to build a helper tool to do syntax checking locally (among other things).

The idea here is that a top-level CLI will delegate to this CLI to handle syntax checks.

This PR adds a simple CLI frontend to this plugin jar and supports 1 command, `syntax`
which will attempt to parse a specified file.

### CODE REVIEW

**Comment by tomzo** [comment]
Hi @marques-work,

Thanks a lot for this. 

I've read the code, it looks OK.
You have done quite a bit refactoring, including the gradle build, did you check if jar still works fine as a plugin in current GoCD?

**Comment by marques-work** [comment]
Hi @tomzo 
> You have done quite a bit refactoring, including the gradle build, did you check if jar still works fine as a plugin in current GoCD?

Yes, indeed. I've installed them to my local GoCD installation and it seems to parse my yaml repo just fine.

**Comment by marques-work** [comment]
@tomzo actually, I want to push up some more cleanup around pipeline export, but relies on this branch. I'll take care of it soon so you can review the new changes.

**Comment by tomzo** [comment]
So I am waiting with merging this. Otherwise I consider this OK.

**Comment by marques-work** [comment]
@tomzo thanks for reviewing. I’ll have this ready by today after I verify that parse and export still work. I’ll ping you once it’s ready.

**Comment by marques-work** [comment]
@tomzo OK, all is ready for final review and (hopefully) merge :). Thanks for waiting.

**Pull request merged**
